ProyectoSGShoots6/Controllers/PaquetesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoSGShoots6.Data;
using ProyectoSGShoots6.Models;
using Microsoft.AspNetCore.Authorization;
namespace ProyectoSGShoots6.Controllers
{
    [Authorize]
    public class PaquetesController : Controller
    {
        private readonly ModelosDBContext _context;

        public PaquetesController(ModelosDBContext context)
        {
            _context = context;
        }

        // GET: Paquetes
        public async Task<IActionResult> Index()
        {
            var modelosDBContext = _context.Paquetes.Include(p => p.TipoPaqueteCodigoNavigation);

            var result = _context.Paquetes.Join(
                _context.Productos,
                paquete => paquete.Id,
                producto => producto.Id,
                (x, y) => new
                {
                    id = x.Id,
                    nombre = x.Nombre,
                    cobertura = x.Cobertura,
                    precio = x.PrecioBasePaquete,
                    idp = y.Id,
                    nombrep = y.Nombre
                }
            );
            return View(await modelosDBContext.ToListAsync());
        }

        // GET: Paquetes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Paquetes == null)
            {
                return NotFound();
            }

            var paquete = await _context.Paquetes
                .Include(p => p.TipoPaqueteCodigoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paquete == null)
            {
                return NotFound();
            }

            return View(paquete);
        }

        // GET: Paquetes/Create
        public IActionResult Create()
        {
            ViewData["TipoPaqueteCodigo"] = new SelectList(_context.TipoPaquetes, "Codigo", "Codigo");
            return View();
        }

        // POST: Paquetes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Cobertura,PrecioBasePaquete,TipoPaqueteCodigo")] Paquete paquete)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paquete);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoPaqueteCodigo"] = new SelectList(_context.TipoPaquetes, "Codigo", "Codigo", paquete.TipoPaqueteCodigo);
            return View(paquete);
        }

        // GET: Paquetes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Paquetes == null)
            {
                return NotFound();
            }

            var paquete = await _context.Paquetes.FindAsync(id);
            if (paquete == null)
            {
                return NotFound();
            }
            ViewData["TipoPaqueteCodigo"] = new SelectList(_context.TipoPaquetes, "Codigo", "Codigo", paquete.TipoPaqueteCodigo);
            return View(paquete);
        }

        // POST: Paquetes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Cobertura,PrecioBasePaquete,TipoPaqueteCodigo")] Paquete paquete)
        {
            if (id != paquete.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paquete);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaqueteExists(paquete.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoPaqueteCodigo"] = new SelectList(_context.TipoPaquetes, "Codigo", "Codigo", paquete.TipoPaqueteCodigo);
            return View(paquete);
        }

        // GET: Paquetes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Paquetes == null)
            {
                return NotFound();
            }

            var paquete = await _context.Paquetes
                .Include(p => p.TipoPaqueteCodigoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paquete == null)
            {
                return NotFound();
            }

            return View(paquete);
        }

        // POST: Paquetes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Paquetes == null)
            {
                return Problem("Entity set 'ModelosDBContext.Paquetes'  is null.");
            }
            var paquete = await _context.Paquetes.FindAsync(id);
            if (paquete != null)
            {
                _context.Paquetes.Remove(paquete);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaqueteExists(int id)
        {
          return (_context.Paquetes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProyectoSGShoots6/Controllers/ProductoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoSGShoots6.Data;
using ProyectoSGShoots6.Models;
using Microsoft.AspNetCore.Authorization;
namespace ProyectoSGShoots6.Controllers
{
    [Authorize]
    public class ProductoesController : Controller
    {
        private readonly ModelosDBContext _context;

        public ProductoesController(ModelosDBContext context)
        {
            _context = context;
        }

        // GET: Productoes
        public async Task<IActionResult> Index()
        {
            var modelosDBContext = _context.Productos.Include(p => p.TipoProductoIdTipoProductoNavigation);
            return View(await modelosDBContext.ToListAsync());
        }

        // GET: Productoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.TipoProductoIdTipoProductoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productoes/Create
        public IActionResult Create()
        {
            ViewData["TipoProductoIdTipoProducto"] = new SelectList(_context.TipoProductos, "IdTipoProducto", "IdTipoProducto");
            return View();
        }

        // POST: Productoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,Estado,TipoProductoIdTipoProducto")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoProductoIdTipoProducto"] = new SelectList(_context.TipoProductos, "IdTipoProducto", "IdTipoProducto", producto.TipoProductoIdTipoProducto);
            return View(producto);
        }

        // GET: Productoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["TipoProductoIdTipoProducto"] = new SelectList(_context.TipoProductos, "IdTipoProducto", "IdTipoProducto", producto.TipoProductoIdTipoProducto);
            return View(producto);
        }

        // POST: Productoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,Estado,TipoProductoIdTipoProducto")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoProductoIdTipoProducto"] = new SelectList(_context.TipoProductos, "IdTipoProducto", "IdTipoProducto", producto.TipoProductoIdTipoProducto);
            return View(producto);
        }

        // GET: Productoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }
            //
            // var result = _dbContext.Customer.Join(
            //     _dbContext.CustomerDetails,
            //     customer => customer.Id,
            //     detail => detail.CustomerId,
            //     (x, y) => new {
            //         id = x.Id,
            //         firstname = x.Firstname,
            //         lastname = x.Lastname,
            //         detailText = y.DetailText
            //     });


            var producto = await _context.Productos
                .Include(p => p.TipoProductoIdTipoProductoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Productos == null)
            {
                return Problem("Entity set 'ModelosDBContext.Productos'  is null.");
            }
            var producto = await _context.Productos.FindAsync(id);
            if (producto != null)
            {
                _context.Productos.Remove(producto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
          return (_context.Productos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProyectoSGShoots6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
@using Microsoft.AspNetCore.Identity
@using ProyectoSGShoots6.Areas.Identity.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<style>
    *{
        font-family:Century Gothic;
    }
.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  right: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}
    body{
        background-image: url("Images/FondoGif.gif");
        font-family: "Lato", sans-serif;
          transition: background-color .5s;
    }
</style>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BySGShoots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ProyectoSGShoots6.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="width:215px; height: 75px; margin: 1rem" src="~/Images/Recurso 26.png"/> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @*
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">PORTFOLIO</a>
                    </li>
                    
                </ul>
            </div>
            *@

            <partial name="_LoginPartial"/>
        </div>
        
    </nav>
    @if (SignInManager.IsSignedIn(User))
                {
                    <div id="mySidenav" class="sidenav">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                        <a asp-controller="Productoes">Productos</a>
                        <a asp-controller="Paquetes">Paquetes</a>
@*                        <a style="margin-left:1rem; margin-right: 1rem" class="nav-link btn btn-outline-light navOpcion" ><span style="color: white">PORTFOLIO</span></a>
*@                        @* <a asp-area="" asp-controller="DetalleProductoController" asp-action="Index">PaquetePredeterminado</a> *@
                        @*<a asp-controller="DetalleProductos">DetalleProducto</a>*@
                        <a asp-controller="Cotizaciones">Cotizaciones</a>

                        @*<a href="#">Productos</a>
                        <a href="#">Portfolio</a>*@
                        <a class="" id="register" asp-area="Identity" asp-page="/Account/Register">Registrar cuenta</a>

                    </div>
                    <div id="main">
                        <span style="font-size:30px;cursor:pointer; color: white;" onclick="openNav()">&#9776; </span>
                    </div>
                }
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    
</div>

   
<footer class=" footer text-muted">
    <div style="color:white" class="container">
        &copy; 2022 - BySGShoots
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      document.getElementById("main").style.marginLeft = "250px";
      document.body.style.backgroundColor = "rgba(0,0,0,0.5)";
    }
    
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      document.getElementById("main").style.marginLeft= "0";
      document.body.style.backgroundColor = "white";
    }
</script>